### ISSUE TITLE
Unable to load .do images

### ISSUE THREAD

**Issue by slembcke** [buserror/mii_emu#12]
A few revisions ago I was able to load .do images with: `--default --drive 6:1:disks/AppleMechanic.do`. This doesn't seem to work anymore. The log seems to suggest it recognizes it, but it won't boot from it and running `pr#6` shows the simulated disk in the left gutter as all black. Other images seem to work fine (.dsk, .po, .hdv).

```
mii_dd_file_load: suffix .do, format 0
mii_dd_drive_load: Disk ][ S:6 D:1 loading disks/AppleMechanic.do
mii_dd_overlay_load: overlay disks/AppleMechanic.miov: No such file or directory
mii_dd_drive_load: No overlay to load, we're fine for now
```

**Comment by buserror** [comment]
Funnily enough, I've been looking at *exactly* that code the last hour, seems I've broken the 'dsk' loader somehow. You CAN go around the problem by renaming (or symlink) it as .DSK as it defaults to dos order. But I'm going to fix it. I've got a whole batch of stuff to push tomorrow

**Comment by buserror** [comment]
Could you try again with version v1.8? I rewrote the 'nibblizer' for DKS/PO/DO's -- I might not have all the combinations tho...

**Comment by slembcke** [comment]
Seems to work now. :+1:
