### ISSUE TITLE
Feature Request: color blending artifacting

### ISSUE THREAD

**Issue by xandark** [buserror/mii_emu#13]
This is an excellent emulator and it would be my daily driver if the visuals looked more like the Apple II video that I remember, which had the blurring and fringing of colors. AppleWin does a good job at this with their NTSC output, but I have to use Wine for that, and that's currently broken on my setup.

**Comment by buserror** [comment]
Do you have a couple of screenshots of what you mean? I added artifacts for HIRES, and the next version I push also have artifacts for DHIRES, so, there's progress! :-)

**Comment by xandark** [comment]
This is taken from the native Linux AppleWin port to SDL. I guess I should've said "I'm looking for NTSC artifacts"... 

![Screenshot 2024-02-28 (14∶48∶37)](https://github.com/buserror/mii_emu/assets/5048913/b32da185-f3db-41c8-87be-0641af407660)

**Comment by buserror** [comment]
I just checked and yes this is a much more complex filter than the one I use -- I mostly do scanlines and some bleed. Perhaps at some point I'll make a shader of some sort to do this in the graphic card!

**Comment by xandark** [comment]
Have you seen this? https://zellyn.com/apple2shader/

**Comment by buserror** [comment]
Yes however after a few discussions, these shaders (not the only one) require a 'full video' decode path, ie all the apple2 memory is passed to the shader to render. This is all very well and good, but I'd like MII to still work on machines with no GPU. I Have Plans for a small device with that on.
I haven;t forgotten about you tho, next version has a new video pipeline, new DHRG color mode, and even a new fancypants low-res/double-lowres renderer. I'm quite happy with how the monochrome looks now, too (bit patterns)
![image](https://github.com/buserror/mii_emu/assets/157201/49c4d02a-f2f4-42d6-80d7-9e95c5fe5801)

**Comment by xandark** [comment]
Hey, that looks nice! And great to hear that you're exploring all the options. I understand about wanting it to be able to run on a non-GPU device, and I imagine these days, it would have to be pretty tiny not to have a GPU, but I'll be following your progress 😊

**Comment by xandark** [comment]
I'm going to close this, I see the new rendering and it's looking very nice now, thank you!

Also read the release notes and am happy to hear about these:

> Added support for 'pasting' text in the emulator. Paste your pet BASIC programs, it works now. (Control-SHIFT-V -- not in a menu yet).
> There is a non-functional Mockingboard driver in the code, it's not hooked up to the UI, it still needs work (mostly make the audio output work).
