### ISSUE TITLE
Clarification on disk file format support

### ISSUE THREAD

**Issue by xandark** [buserror/mii_emu#14]
Could the documentation specifically indicate which disk image file types that this really cool emulator supports?

**Comment by buserror** [comment]
I will double check that. FYI it read/writes .WOZ (1 & 2) and has read only support for NIB, DSK, PO and DO floppy images. I can also write to .HDV and .PO smartport images (via a 'overlay' file that leaves the original file intact)
I MIGHT add write support for NIB, and perhaps DSK... Altho I'm not entirely sure this is needed...

**Comment by xandark** [comment]
Okay that's good to know in one place.

**Comment by buserror** [comment]
I'm closing this because MII now supports write for all the supported formats, so I think that more or less clarify the problem? Feel free to re-open if you like!
