### ISSUE TITLE
NOTE: created an Arch Linux AUR package for mii_emu

### ISSUE THREAD

**Issue by ajacocks** [buserror/mii_emu#18]
I really enjoy this emulator, so I created a simple AUR package for Arch Linux for mii_emu:

[](https://aur.archlinux.org/packages/mii_emu)

If you have the time, please take a look at how I am building the package:

[](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mii_emu)

I specifically blocked the `-flto=auto` CFLAG. This is because it causes the package not to build, with the following error:

```
/tmp/ccg8rfRK.s: Assembler messages:
/tmp/ccg8rfRK.s:49: Error: file not found: roms/mii_rom_scc_3410065a.bin
/tmp/ccg8rfRK.s:68: Error: file not found: fonts/Charcoal_mui.ttf
/tmp/ccg8rfRK.s:87: Error: file not found: fonts/typicon.ttf
/tmp/ccg8rfRK.s:106: Error: file not found: fonts/Dingbat.ttf
/tmp/ccg8rfRK.s:125: Error: file not found: fonts/Geneva.ttf
make[1]: *** [/tmp/ccoLwk6e.mk:2: /tmp/ccyJ4d3L.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:146: build-x86_64-pc-linux-gnu/bin/mii_emu_gl] Error 1
```

I blocked `-fno-omit-frame-pointer` because you disabled it in your Makefile. Not sure why, but I assumed that you had a reason.

Both of these are default CFLAGS for packages built on Arch Linux.

With these minor build changes, everything seems to work fine.

**Comment by buserror** [comment]
Thanks. I think the LTO problem is due to incbin.h which add linker sections with binary bits. Super handy, but this seem to be problematic -- so might convert all the binaries to .h files with xxd and use that for the next version...

no-omit-frame-pointer helps for debugging and profiling. Otherwise you sometimes have no meaningful stack trace. We don't need frame pointers for normal builds, but I sometimes do! :-)

**Comment by buserror** [comment]
Next version has removed the use of incbin.h, so this should "soon" be resolved.

**Comment by ajacocks** [comment]
Excellent. I will update the build when you release it.

Off topic, I'd love to see Ample (MAME front end for Apple machines) with
your UI. I've started looking at how hard that would be.

- Alex

**Comment by buserror** [comment]
If you have any ideas on what to add for libmui to make it better for the job, feel free to add issues on that project as well!

**Comment by buserror** [comment]
I've now pushed v1.95 that removed incbin.h from both mii and libmui, so that problem should be gone...?

**Comment by ajacocks** [comment]
You didn't tag it as a release, though?

**Comment by buserror** [comment]
@ajacocks I've now tagged v1.96 BTW...

**Comment by ajacocks** [comment]
Thank you, I’ll update my builds.

**Comment by buserror** [comment]
Are you happy to close this now? All worky? ;-)

**Comment by ajacocks** [comment]
Yep, it seems to work perfectly
