### ISSUE TITLE
Documentation: Running on WSL

### ISSUE THREAD

**Issue by ahrens26** [buserror/mii_emu#19]
I was able to run MII under WSL (Debian) with just a few extra steps. Perhaps the below can be added to the "How to I compile it and run it?" section of the project readme:

1. `sudo apt install libasound2-plugins`
2. `nano ~/.asoundrc`, and add these two lines:
```shell
pcm.default pulse
ctl.default pulse
``` 
3. Restart WSL

**Comment by buserror** [comment]
That was added to the Compiling.md, thanks
