### ISSUE TITLE
about windows/macos port

### ISSUE THREAD

**Issue by iolo** [buserror/mii_emu#2]
Hi,
Most of all, it looks clean & promising.
Do you have any plan to port to windows and/or macos?

**Comment by buserror** [comment]
Not really. I'm told it works on WSL (bar the audio) but I haven't powered my hackintosh for a loooong time so... :-) -- for OSX it would require a new front-end, the X11 one won't work. Native GLU/GLEW? not sure!

**Comment by iolo** [comment]
I found just **TWO** stuffs uses X11.
- contrib/libsofd.h for file chooser dialog UI
- nuklear/nuklear_xlib_gl3.h for minimal X11 abstraction

Cool!

I'll try to port these layers to macos.

I'll close this issue.
