### ISSUE TITLE
window resizing not refreshed when CPU stopped

### ISSUE THREAD

**Issue by Skippyfr** [buserror/mii_emu#21]
When the CPU runs, you can resize the MII window application, and the Apple II screen is properly resized in the window. If the CPU is stopped, the Apple II screen is not resized. odd behavior.

**Comment by buserror** [comment]
Seems to work fine here BTW. Also changed quite a bit of that code in the last versions; adding full screen etc so I'm quietly confident this works properly -- at least on my 2 testing setups! Feel free to re-open if I'm wrong, and thanks for the  report tho! :-)

**Comment by Skippyfr** [comment]
yes it is fixed . great!
