### ISSUE TITLE
Request: Joystick support

### ISSUE THREAD

**Issue by BlastBlaster17** [buserror/mii_emu#23]
One of the main features of the Apple II was joystick support. In fact, most games from this era require joysticks because the cursor keys sucked. And I noticed that there's nothing in the code that mentions joysticks. I think there should be a way to map your keyboard to joystick buttons and axes on an Apple II joystick so you could use a virtual joystick. And maybe there should also be some default mappings for some common types of controllers like Xbox, DualShock/Sense, Pro controllers, Joy-Cons, etc. This would make it easy to play all sorts of arcade game ports like Donkey Kong and Pac-Man, among others. I think this should be possible; all you would have to do is attach a virtual device to the joystick port and have pressing the bound buttons simulate button presses on the joystick. I think DOSBox and its variants do something similar to this.

**Comment by buserror** [comment]
MII supports Joystick. Typical USB joystick will work. I use one of these:
https://www.amazon.co.uk/gp/product/B07V2P79Z2/

Just plug it and it'll work :-)

**Comment by BlastBlaster17** [comment]
I think I can use AntiMicroX if I want to play with the keyboard and just hate the layout.
