### ISSUE TITLE
Amber shows up as a blue screen

### ISSUE THREAD

**Issue by xandark** [buserror/mii_emu#5]
I'm running KDE neon, which is essentially Ubuntu 22.04 with latest KDE packages.

![Screenshot 2023-10-27 (20∶36∶20)](https://github.com/buserror/mii_emu/assets/5048913/a6b26286-674e-4427-b8a1-6db9cdffd8a3)

**Comment by buserror** [comment]
How bizarre! I made a change yesterday that changed RGB toi BGR, and I forgot to change the Amber mode, sorry :-) -- will push some patches later anyway will be fixed in a jiffie

**Comment by buserror** [comment]
Fixed on latest tree
