### ISSUE TITLE
Booting from a disk image?

### ISSUE THREAD

**Issue by slembcke** [buserror/mii_emu#8]
This might be a real dumb question, but how do you boot from a disk image? I've had some mild fun playing with the basic and monitor prompts (I will never not remember call -151!), but I cannot figure out how to get it to boot from an image.

I tried: `mii_emu --default --drive 6:1:disks/dos33master.nib` for example (with and without `--default`). The console says
```
_mii_disk2_command: drive 0 loading disks/dos33master.nib
disk_format_load loaded disks/dos33master.nib dz = 232960
```
but it doesn't seem to do anything? It doesn't boot from the disk, and doesn't load the dos commands, etc. If I run the `disk list` command inside the Mii shell it just says the "ID Card  Name" headers, and lists no disks.

I'm pretty stumped. :-\ Maybe just throw in a couple example command lines in the readme? Especially since you ship with a few disk images.

**Comment by buserror** [comment]
AH it is what I think is a bug somewhere in my Smartport probing... --default install a DiskII card in Slot 6, and a Smartport card in Slot 7 -- and it tries to boot 7 first, and if there's no disk, it stops... That's wrong it SHOULD then probe slot 6...
Anyway from the proimpt you can boot slot #6 'manually' with PR#6 -- that will work!
Or, remove --default and use -s 6:disk2 instead, that will prevent the smartport card to be installed!.

I'll keep this bug open, because there IS a bug :-)

**Comment by slembcke** [comment]
Got it. Thanks! :D Assigning the slots manually worked. I could not for the life of me remember the PR#6 trick either. There's plenty of Apple ][ info around on the internet, but searching for quick answers doesn't really work. >_> Anyway, thanks! Now I just need to get cc65 set up for ][ some mild C based fun again!

**Comment by WizardOfWor1969** [comment]
**If there is a space in the passed name/path, it does not work. Something like:**
./mii_emu -s 6:disk2 -d 6:1:'/home/adamchall/Desktop/Apple DOS 3.3 August 1980.dsk' 
or 
./mii_emu -s 6:disk2 -d 6:1:"/home/adamchall/Desktop/Apple DOS 3.3 August 1980.dsk"

**gives you** 

_mii_disk2_init loading in slot 6
_mii_disk2_command: drive 0 loading /home/adamchall/Desktop/Apple
Couldn't load/mmap disk /home/adamchall/Desktop/Apple: No such file or directory

It seems at first glance that disk emulation is much slower than a real Apple II, but I could be wrong about that.

I can open these as  seperate issue(s), but as I just started using the emulator , I thought I mention them here first.

**Comment by slembcke** [comment]
> It seems at first glance that disk emulation is much slower than a real Apple II, but I could be wrong about that.

Hmm. I kind of noticed that too. I got my real ][e setup again after playing with this, and loading seemed _much_ faster on it. Though I guess I should measure it on the same file or something to be sure.

**Comment by buserror** [comment]
This report isn't really relevant to 1.5 -- pretty much everything has changed in the startup options, and there is now a UI to pick disks for drives etc...

**Comment by WizardOfWor1969** [comment]
Still does not work, can not handle spaces passed.
